"""
Amira FinIQ — Synthetic Data Generator for SQLite (Local Development)
=====================================================================
Generates realistic synthetic data for all 17 tables and 3 views in the
FinIQ UC Documentation schema, stored in a local SQLite database.

This is the SQLite equivalent of databricks_synthetic_data.py for local
development and testing without a Databricks environment.

Usage:
  python generate_synthetic_data_sqlite.py

Output: finiq_synthetic.db in the same directory as this script.
Seed=42 for full reproducibility.

Source schema: Matt Hutton's FinIQ UC Documentation (46 pages, 2026-03-25)
Author: Amira Technologies (generated by Claude)
Date: 2026-03-26
"""

import sqlite3
import json
import random
import hashlib
import math
import os
from datetime import datetime

# ============================================================================
# CONFIGURATION
# ============================================================================

SEED = 42
FISCAL_YEARS = [2024, 2025]       # FY2024 and FY2025
PERIODS_PER_YEAR = 13             # Mars uses 13-period fiscal calendar
BASE_REVENUE_MILLIONS = 45000     # ~$45B annual revenue (Mars scale)
ORGANIC_GROWTH_RATE = 0.05        # 5% organic growth target
NUM_CUSTOMERS = 55                # 55 realistic retail/wholesale customers
NUM_COMPOSITE_ITEMS = 110         # 110+ product rows

DB_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "finiq_synthetic.db")

random.seed(SEED)

print(f"Configuration loaded: DB={DB_PATH}")
print(f"Fiscal years: {FISCAL_YEARS}, Seed: {SEED}")

# ============================================================================
# HELPERS
# ============================================================================

def gen_entity_id(name):
    """Generate a deterministic entity ID from the name."""
    h = hashlib.md5(name.encode()).hexdigest()[:6].upper()
    return f"E{h}"


def get_currency(entity_name):
    """Determine currency from entity name."""
    if any(x in entity_name for x in ["US", "USA", "Canada", "NA", "North America"]):
        return "USD"
    elif any(x in entity_name for x in ["UK", "Ireland"]):
        return "GBP"
    elif any(x in entity_name for x in ["Europe", "France", "Germany", "Italy", "Spain",
                                         "Netherlands", "Belgium", "Austria", "Portugal"]):
        return "EUR"
    elif any(x in entity_name for x in ["Japan"]):
        return "JPY"
    elif any(x in entity_name for x in ["China", "Coastal", "Inland"]):
        return "CNY"
    elif any(x in entity_name for x in ["Australia", "ANZ", "New Zealand"]):
        return "AUD"
    elif any(x in entity_name for x in ["Brazil"]):
        return "BRL"
    elif any(x in entity_name for x in ["Mexico"]):
        return "MXN"
    elif any(x in entity_name for x in ["India"]):
        return "INR"
    elif any(x in entity_name for x in ["Korea"]):
        return "KRW"
    elif any(x in entity_name for x in ["Thailand"]):
        return "THB"
    elif any(x in entity_name for x in ["Indonesia"]):
        return "IDR"
    elif any(x in entity_name for x in ["Russia"]):
        return "RUB"
    elif any(x in entity_name for x in ["UAE"]):
        return "AED"
    elif any(x in entity_name for x in ["Saudi"]):
        return "SAR"
    elif any(x in entity_name for x in ["South Africa"]):
        return "ZAR"
    elif any(x in entity_name for x in ["Poland", "Czech"]):
        return "PLN"
    return "USD"


# FX rates to USD (approximate, for synthetic data)
fx_rates = {
    "USD": 1.0, "GBP": 1.27, "EUR": 1.08, "JPY": 0.0067, "CNY": 0.14,
    "AUD": 0.65, "BRL": 0.20, "MXN": 0.058, "INR": 0.012, "KRW": 0.00075,
    "THB": 0.028, "IDR": 0.000063, "RUB": 0.011, "AED": 0.27, "SAR": 0.27,
    "ZAR": 0.054, "PLN": 0.25,
}


def generate_base_revenue(entity_id, date_id, acct_id):
    """
    Generate a deterministic but realistic base USD value for a given entity/date/account.
    Includes organic growth (~5%) and mild seasonality.
    """
    # Deterministic seed per combination
    combo_hash = hash((entity_id, date_id, acct_id)) % 2**31
    rng = random.Random(combo_hash)

    year = date_id // 100
    period = date_id % 100

    # Base value varies by account type
    if acct_id == "S900077":  # Net Revenue
        base = rng.uniform(80, 350)
    elif acct_id in ("FR4100",):  # Gross Profit
        base = rng.uniform(35, 170)
    elif acct_id in ("FR4200", "SR4001"):  # COGS
        base = rng.uniform(40, 200)
    elif acct_id in ("S900083", "S900123"):  # Total/Organic Growth (bps)
        base = rng.uniform(200, 800)
    elif acct_id in ("S900227",):  # OG%
        base = rng.uniform(3.0, 8.0)
    elif acct_id in ("S900067", "S900070", "S900069"):  # Volume/Price/Mix (bps)
        base = rng.uniform(-200, 500)
    elif acct_id in ("MR5200", "MR5100"):  # A&CP
        base = rng.uniform(8, 50)
    elif acct_id in ("SR5101", "SR5103"):  # Media/Digital
        base = rng.uniform(3, 20)
    elif acct_id in ("MR8005",):  # A&CP Shape %
        base = rng.uniform(8.0, 15.0)
    elif acct_id in ("SR6102", "SR6153"):  # Overhead/R&D
        base = rng.uniform(5, 35)
    elif acct_id in ("MR8004",):  # CE Shape
        base = rng.uniform(25.0, 40.0)
    elif acct_id in ("MR6300",):  # Total Overhead
        base = rng.uniform(10, 50)
    elif acct_id in ("MR6359", "MR8003"):  # OH % / OH Shape %
        base = rng.uniform(5.0, 12.0)
    elif acct_id in ("S900144",):  # Operating Profit
        base = rng.uniform(10, 60)
    elif acct_id in ("S900233",):  # OP Margin %
        base = rng.uniform(8.0, 18.0)
    elif acct_id in ("S900130",):  # EBITDA
        base = rng.uniform(15, 70)
    elif acct_id in ("ST9020",):  # Segment Profit
        base = rng.uniform(8, 45)
    elif acct_id in ("CF8129",):  # Cash from Operations
        base = rng.uniform(5, 40)
    elif acct_id in ("CF8133",):  # CapEx
        base = rng.uniform(2, 15)
    elif acct_id in ("MC8136",):  # Working Capital
        base = rng.uniform(-5, 10)
    elif acct_id in ("MC8149", "CF8147", "MC8913"):  # Inventory/AR/AP
        base = rng.uniform(3, 25)
    elif acct_id in ("S900147",):  # NCFO
        base = rng.uniform(3, 30)
    elif acct_id in ("MC8100",):  # Depreciation
        base = rng.uniform(2, 12)
    elif acct_id in ("MC8902",):  # Other Cash
        base = rng.uniform(-3, 5)
    else:
        base = rng.uniform(1, 20)

    # Apply organic growth: ~5% per year, compounding by period
    growth_factor = 1.0
    if year == 2025:
        growth_factor = 1.0 + ORGANIC_GROWTH_RATE
    # Sub-period growth within the year
    growth_factor *= (1.0 + ORGANIC_GROWTH_RATE / PERIODS_PER_YEAR * (period - 7))

    # Seasonal pattern: holiday bump in Q4 (P10-P13), slight dip in Q1
    seasonal = 1.0
    if period >= 10:
        seasonal = 1.0 + rng.uniform(0.05, 0.15)
    elif period <= 3:
        seasonal = 1.0 - rng.uniform(0.02, 0.08)

    # Random noise: +/- 5%
    noise = rng.uniform(0.95, 1.05)

    return round(base * growth_factor * seasonal * noise, 2)


# ============================================================================
# DATABASE SETUP
# ============================================================================

# Remove existing DB for a clean start
if os.path.exists(DB_PATH):
    os.remove(DB_PATH)

conn = sqlite3.connect(DB_PATH)
cur = conn.cursor()

# Enable WAL mode for better performance during bulk inserts
cur.execute("PRAGMA journal_mode=WAL")
cur.execute("PRAGMA synchronous=NORMAL")

table_counts = {}

# ============================================================================
# TABLE 1: finiq_date (4 cols)
# ============================================================================
print("\nCreating TABLE 1: finiq_date ...")

cur.execute("""
CREATE TABLE finiq_date (
    Date_ID     INTEGER NOT NULL,
    Year        INTEGER NOT NULL,
    Period      TEXT    NOT NULL,
    Quarter     TEXT    NOT NULL
)
""")

date_rows = []
for fy in FISCAL_YEARS:
    for p in range(1, PERIODS_PER_YEAR + 1):
        date_id = fy * 100 + p
        period_str = f"P{p:02d}"
        if p <= 3:
            quarter = "Q1"
        elif p <= 6:
            quarter = "Q2"
        elif p <= 9:
            quarter = "Q3"
        else:
            quarter = "Q4"
        date_rows.append((date_id, fy, period_str, quarter))

cur.executemany("INSERT INTO finiq_date VALUES (?,?,?,?)", date_rows)
table_counts["finiq_date"] = len(date_rows)
print(f"  Wrote finiq_date: {len(date_rows)} rows")

# ============================================================================
# TABLE 2: finiq_dim_entity (5 cols)
# ============================================================================
print("\nCreating TABLE 2: finiq_dim_entity ...")

cur.execute("""
CREATE TABLE finiq_dim_entity (
    Parent_Entity_ID  TEXT    NOT NULL,
    Parent_Entity     TEXT    NOT NULL,
    Child_Entity_ID   TEXT    NOT NULL,
    Child_Entity      TEXT    NOT NULL,
    Entity_Level      INTEGER NOT NULL
)
""")

# --- Define the full org hierarchy ---
org_tree = {
    "Mars Inc": {
        "Petcare": {
            "Royal Canin": {
                "RC Europe": ["RC France", "RC Germany", "RC UK", "RC Italy", "RC Spain", "RC Nordics"],
                "RC North America": ["RC USA East", "RC USA West", "RC Canada"],
                "RC Asia Pacific": ["RC China", "RC Japan", "RC Australia", "RC Southeast Asia"],
                "RC Latin America": ["RC Brazil", "RC Mexico"],
            },
            "Mars Petcare NA": {
                "MPC US": ["MPC US Northeast", "MPC US Southeast", "MPC US Central", "MPC US West"],
                "MPC Canada": ["MPC Canada East", "MPC Canada West"],
            },
            "Mars Petcare Europe": {
                "MPC UK & Ireland": ["MPC UK", "MPC Ireland"],
                "MPC Central Europe": ["MPC Germany", "MPC Austria", "MPC Switzerland"],
                "MPC Southern Europe": ["MPC France", "MPC Italy", "MPC Spain", "MPC Portugal"],
                "MPC Northern Europe": ["MPC Netherlands", "MPC Belgium", "MPC Nordics"],
                "MPC Eastern Europe": ["MPC Poland", "MPC Czech Republic", "MPC Russia"],
            },
            "Mars Petcare Asia": {
                "MPC Greater China": ["MPC China Coastal", "MPC China Inland"],
                "MPC Japan Korea": ["MPC Japan", "MPC South Korea"],
                "MPC ANZ": ["MPC Australia", "MPC New Zealand"],
                "MPC SEA": ["MPC Thailand", "MPC Indonesia", "MPC Philippines"],
            },
        },
        "Snacking": {
            "Mars Wrigley NA": {
                "MW US": ["MW US East", "MW US Central", "MW US West", "MW US South"],
                "MW Canada": ["MW Canada East", "MW Canada West"],
            },
            "Mars Wrigley Europe": {
                "MW UK & Ireland": ["MW UK", "MW Ireland"],
                "MW Central Europe": ["MW Germany", "MW Austria", "MW Switzerland", "MW Poland"],
                "MW Southern Europe": ["MW France", "MW Italy", "MW Spain"],
                "MW Northern Europe": ["MW Netherlands", "MW Belgium", "MW Nordics"],
                "MW Russia CIS": ["MW Russia", "MW Ukraine", "MW Kazakhstan"],
            },
            "Mars Wrigley Asia Pacific": {
                "MW Greater China": ["MW China East", "MW China West"],
                "MW Japan Korea": ["MW Japan", "MW South Korea"],
                "MW ANZ": ["MW Australia", "MW New Zealand"],
                "MW India": ["MW India North", "MW India South"],
                "MW SEA": ["MW Thailand", "MW Indonesia", "MW Vietnam"],
            },
            "Mars Wrigley Latin America": {
                "MW Brazil": ["MW Brazil South", "MW Brazil North"],
                "MW Mexico": ["MW Mexico North", "MW Mexico South"],
                "MW Andean": ["MW Colombia", "MW Peru", "MW Chile"],
            },
        },
        "Food Nutrition & Multisales": {
            "Mars Food North America": {
                "MF US": ["MF US East", "MF US West", "MF US Central"],
                "MF Canada": ["MF Canada"],
            },
            "Mars Food Europe": {
                "MF UK & Ireland": ["MF UK", "MF Ireland"],
                "MF Continental Europe": ["MF Germany", "MF France", "MF Italy", "MF Spain"],
                "MF ANZ": ["MF Australia", "MF New Zealand"],
            },
            "Mars Multisales": {
                "MS Middle East Africa": ["MS UAE", "MS Saudi Arabia", "MS South Africa", "MS Egypt"],
                "MS Central Asia": ["MS Turkey", "MS Pakistan"],
            },
        },
        "Wrigley": {
            "Wrigley North America": {
                "WR US": ["WR US East", "WR US West"],
                "WR Canada": ["WR Canada"],
            },
            "Wrigley International": {
                "WR Europe": ["WR UK", "WR Germany", "WR France"],
                "WR Asia": ["WR China", "WR India", "WR Japan"],
                "WR LATAM": ["WR Brazil", "WR Mexico"],
            },
        },
    }
}

entity_rows = []
entity_counter = [0]


def walk_org(tree, parent_name, parent_id, level):
    """Recursively walk the org tree and generate entity rows."""
    for child_name, subtree in tree.items():
        child_id = gen_entity_id(child_name)
        entity_rows.append((parent_id, parent_name, child_id, child_name, level))
        entity_counter[0] += 1
        if isinstance(subtree, dict):
            walk_org(subtree, child_name, child_id, level + 1)
        elif isinstance(subtree, list):
            for sub in subtree:
                sub_id = gen_entity_id(sub)
                entity_rows.append((child_id, child_name, sub_id, sub, level + 1))
                entity_counter[0] += 1


# Root: Mars Inc is its own parent at level 1
mars_id = gen_entity_id("Mars Inc")
entity_rows.append((mars_id, "Mars Inc", mars_id, "Mars Inc", 1))
entity_counter[0] += 1

# Walk the tree starting at level 2 (GBU)
walk_org(org_tree["Mars Inc"], "Mars Inc", mars_id, 2)

cur.executemany("INSERT INTO finiq_dim_entity VALUES (?,?,?,?,?)", entity_rows)
table_counts["finiq_dim_entity"] = len(entity_rows)
print(f"  Wrote finiq_dim_entity: {len(entity_rows)} rows")

# ============================================================================
# TABLE 3: finiq_dim_account (6 cols)
# array<string> columns stored as JSON strings
# ============================================================================
print("\nCreating TABLE 3: finiq_dim_account ...")

cur.execute("""
CREATE TABLE finiq_dim_account (
    Parent_Account_ID  TEXT    NOT NULL,
    Parent_Account     TEXT    NOT NULL,
    Child_Account_ID   TEXT    NOT NULL,
    Child_Account      TEXT    NOT NULL,
    Sign_Conversion    INTEGER NOT NULL,
    Statement          TEXT    NOT NULL
)
""")

accounts_data = [
    # --- P&L Statement accounts ---
    ("S900083", "Total Growth",          ["S900083"],                    ["Total Growth"],                        1,  ["P&L"]),
    ("S900123", "Organic Growth",        ["S900083"],                    ["Total Growth"],                        1,  ["P&L"]),
    ("S900227", "Organic Growth %",      ["S900083", "S900123"],         ["Total Growth", "Organic Growth"],      1,  ["P&L"]),
    ("S900067", "Volume",                ["S900083", "S900123"],         ["Total Growth", "Organic Growth"],      1,  ["P&L"]),
    ("S900070", "Price",                 ["S900083", "S900123"],         ["Total Growth", "Organic Growth"],      1,  ["P&L"]),
    ("S900069", "Mix",                   ["S900083", "S900123"],         ["Total Growth", "Organic Growth"],      1,  ["P&L"]),
    ("S900077", "Net Revenue",           ["S900077"],                    ["Net Revenue"],                         1,  ["P&L"]),
    ("FR4100",  "Gross Profit",          ["S900077"],                    ["Net Revenue"],                         1,  ["P&L"]),
    ("FR4200",  "Cost of Goods Sold",    ["S900077"],                    ["Net Revenue"],                        -1,  ["P&L"]),
    ("SR4001",  "Material Costs",        ["S900077", "FR4200"],          ["Net Revenue", "Cost of Goods Sold"],  -1,  ["P&L"]),
    ("FR4300",  "Distribution Costs",    ["S900077"],                    ["Net Revenue"],                        -1,  ["P&L"]),
    ("FR4000",  "MAC Shape",             ["S900077"],                    ["Net Revenue"],                         1,  ["P&L"]),
    ("MR5200",  "A&CP Total",            ["S900077", "FR4000"],          ["Net Revenue", "MAC Shape"],           -1,  ["P&L"]),
    ("MR5100",  "Advertising",           ["S900077", "FR4000", "MR5200"],["Net Revenue", "MAC Shape", "A&CP Total"], -1, ["P&L"]),
    ("SR5101",  "Media Spend",           ["S900077", "MR5200"],          ["Net Revenue", "A&CP Total"],          -1,  ["P&L"]),
    ("SR5103",  "Digital Marketing",     ["S900077", "MR5200"],          ["Net Revenue", "A&CP Total"],          -1,  ["P&L"]),
    ("MR8005",  "A&CP Shape %",          ["S900077"],                    ["Net Revenue"],                         1,  ["P&L"]),
    ("SR6102",  "Controllable Overhead", ["S900077"],                    ["Net Revenue"],                        -1,  ["P&L"]),
    ("SR6153",  "R&D Expense",           ["S900077", "SR6102"],          ["Net Revenue", "Controllable Overhead"], -1, ["P&L"]),
    ("MR8004",  "CE Shape",              ["S900077"],                    ["Net Revenue"],                         1,  ["P&L"]),
    ("MR6300",  "Total Overhead",        ["S900077"],                    ["Net Revenue"],                        -1,  ["P&L"]),
    ("MR6359",  "Controllable OH %",     ["S900077"],                    ["Net Revenue"],                         1,  ["P&L"]),
    ("MR8003",  "Controllable OH Shape %",["S900077"],                   ["Net Revenue"],                         1,  ["P&L"]),
    ("S900144", "Operating Profit",      ["S900077"],                    ["Net Revenue"],                         1,  ["P&L"]),
    ("S900233", "OP Margin %",           ["S900077"],                    ["Net Revenue"],                         1,  ["P&L"]),
    ("S900130", "EBITDA",                ["S900077"],                    ["Net Revenue"],                         1,  ["P&L"]),
    ("ST9020",  "Segment Profit",        ["S900077"],                    ["Net Revenue"],                         1,  ["P&L"]),

    # --- NCFO Statement accounts ---
    ("CF8129",  "Cash from Operations",  ["CF8129"],                     ["Cash from Operations"],                1,  ["NCFO"]),
    ("CF8133",  "Capital Expenditure",   ["CF8129"],                     ["Cash from Operations"],               -1,  ["NCFO"]),
    ("MC8136",  "Working Capital",       ["CF8129"],                     ["Cash from Operations"],               -1,  ["NCFO"]),
    ("MC8149",  "Inventory",             ["CF8129", "MC8136"],           ["Cash from Operations", "Working Capital"], -1, ["NCFO"]),
    ("CF8147",  "Accounts Receivable",   ["CF8129", "MC8136"],           ["Cash from Operations", "Working Capital"], -1, ["NCFO"]),
    ("MC8913",  "Accounts Payable",      ["CF8129", "MC8136"],           ["Cash from Operations", "Working Capital"],  1, ["NCFO"]),
    ("S900147", "NCFO",                  ["S900147"],                    ["NCFO"],                                1,  ["NCFO"]),
    ("MC8100",  "Depreciation",          ["CF8129"],                     ["Cash from Operations"],                1,  ["NCFO"]),
    ("MC8902",  "Other Cash Items",      ["CF8129"],                     ["Cash from Operations"],                1,  ["NCFO"]),
]

account_rows_db = []
for child_id, child_name, parent_ids, parent_names, sign, stmts in accounts_data:
    account_rows_db.append((
        json.dumps(parent_ids),
        json.dumps(parent_names),
        child_id,
        child_name,
        sign,
        json.dumps(stmts),
    ))

cur.executemany("INSERT INTO finiq_dim_account VALUES (?,?,?,?,?,?)", account_rows_db)
table_counts["finiq_dim_account"] = len(account_rows_db)
print(f"  Wrote finiq_dim_account: {len(account_rows_db)} rows")

# ============================================================================
# TABLE 4: finiq_account_formula (4 cols)
# ============================================================================
print("\nCreating TABLE 4: finiq_account_formula ...")

cur.execute("""
CREATE TABLE finiq_account_formula (
    Account     TEXT NOT NULL,
    Formula     TEXT NOT NULL,
    Components  TEXT NOT NULL,
    Old_RL      TEXT NOT NULL
)
""")

formula_data = [
    ("S900227", "S900123 / S900077 * 100",    ["S900123", "S900077"],         ["OG_PCT"]),
    ("S900083", "S900067 + S900070 + S900069", ["S900067", "S900070", "S900069"], ["TOTAL_GROWTH"]),
    ("FR4100",  "S900077 - FR4200",            ["S900077", "FR4200"],          ["GP"]),
    ("FR4000",  "FR4100 - MR5200",             ["FR4100", "MR5200"],           ["MAC"]),
    ("MR8005",  "MR5200 / S900077 * 100",      ["MR5200", "S900077"],          ["ACP_SHAPE"]),
    ("MR8004",  "FR4000 - SR6102",             ["FR4000", "SR6102"],           ["CE"]),
    ("MR6359",  "SR6102 / S900077 * 100",      ["SR6102", "S900077"],          ["COH_PCT"]),
    ("MR8003",  "MR6300 / S900077 * 100",      ["MR6300", "S900077"],          ["COH_SHAPE"]),
    ("S900233", "S900144 / S900077 * 100",     ["S900144", "S900077"],         ["OP_MARGIN"]),
    ("S900147", "CF8129 - CF8133",             ["CF8129", "CF8133"],           ["NCFO"]),
    ("MC8136",  "MC8149 + CF8147 - MC8913",    ["MC8149", "CF8147", "MC8913"], ["WC"]),
]

formula_rows_db = [(acct, formula, json.dumps(comps), json.dumps(old_rl))
                   for acct, formula, comps, old_rl in formula_data]

cur.executemany("INSERT INTO finiq_account_formula VALUES (?,?,?,?)", formula_rows_db)
table_counts["finiq_account_formula"] = len(formula_rows_db)
print(f"  Wrote finiq_account_formula: {len(formula_rows_db)} rows")

# ============================================================================
# TABLE 5: finiq_account_input (3 cols)
# ============================================================================
print("\nCreating TABLE 5: finiq_account_input ...")

cur.execute("""
CREATE TABLE finiq_account_input (
    Statement   TEXT    NOT NULL,
    Account_ID  TEXT    NOT NULL,
    Generation  INTEGER NOT NULL
)
""")

account_input_rows = []
gen_counter = 1
for child_id, child_name, _, _, _, stmts in accounts_data:
    for stmt in set(stmts):
        account_input_rows.append((stmt, child_id, gen_counter))
        gen_counter += 1

cur.executemany("INSERT INTO finiq_account_input VALUES (?,?,?)", account_input_rows)
table_counts["finiq_account_input"] = len(account_input_rows)
print(f"  Wrote finiq_account_input: {len(account_input_rows)} rows")

# ============================================================================
# TABLE 6: finiq_composite_item (12 cols)
# ============================================================================
print("\nCreating TABLE 6: finiq_composite_item ...")

cur.execute("""
CREATE TABLE finiq_composite_item (
    Composite_Item_ID       TEXT    NOT NULL,
    EC_Group                TEXT,
    Technology              TEXT,
    Supply_Tech             TEXT,
    Segment                 TEXT,
    Business_Segment        TEXT,
    Market_Segment          TEXT,
    Brand_ID                INTEGER,
    Brand                   TEXT,
    Consumer_Pack_Format    TEXT,
    Product_Consolidation   TEXT,
    Product_Category        TEXT
)
""")

brand_products = {
    "Pedigree": {
        "gbu": "Petcare", "ec_group": "Pet Food", "technology": "Dry",
        "supply_tech": "Extrusion", "segment": "Dog Food",
        "business_segment": "Mainstream Dog", "market_segment": "Dog Dry",
        "products": [
            ("Adult Complete Nutrition", "Bag 15lb", "Dry Dog Food", "Dog Nutrition"),
            ("Puppy Growth & Protection", "Bag 15lb", "Dry Dog Food", "Dog Nutrition"),
            ("High Protein Beef & Lamb", "Bag 18lb", "Dry Dog Food", "Dog Nutrition"),
            ("Small Dog Complete", "Bag 3.5lb", "Dry Dog Food", "Dog Nutrition"),
            ("Dentastix Original", "Pack 32ct", "Dog Treats", "Dog Dental"),
            ("Dentastix Fresh", "Pack 28ct", "Dog Treats", "Dog Dental"),
            ("Choice Cuts in Gravy", "Can 13.2oz", "Wet Dog Food", "Dog Nutrition"),
            ("Chopped Ground Dinner", "Can 13.2oz", "Wet Dog Food", "Dog Nutrition"),
        ]
    },
    "Whiskas": {
        "gbu": "Petcare", "ec_group": "Pet Food", "technology": "Wet",
        "supply_tech": "Retort", "segment": "Cat Food",
        "business_segment": "Mainstream Cat", "market_segment": "Cat Wet",
        "products": [
            ("Meaty Selections", "Pouch 3oz 12pk", "Wet Cat Food", "Cat Nutrition"),
            ("Seafood Selections", "Pouch 3oz 12pk", "Wet Cat Food", "Cat Nutrition"),
            ("Purrfectly Chicken", "Can 5.5oz", "Wet Cat Food", "Cat Nutrition"),
            ("Temptations Classic", "Tub 16oz", "Cat Treats", "Cat Snacks"),
            ("Temptations Mixups", "Pack 6.3oz", "Cat Treats", "Cat Snacks"),
            ("Indoor Cat Dry", "Bag 6lb", "Dry Cat Food", "Cat Nutrition"),
        ]
    },
    "Royal Canin": {
        "gbu": "Petcare", "ec_group": "Veterinary Nutrition", "technology": "Dry",
        "supply_tech": "Precision Extrusion", "segment": "Premium Pet",
        "business_segment": "Veterinary", "market_segment": "Vet Diet",
        "products": [
            ("Breed Health Nutrition German Shepherd", "Bag 30lb", "Breed Specific", "Premium Dog"),
            ("Breed Health Nutrition French Bulldog", "Bag 17lb", "Breed Specific", "Premium Dog"),
            ("Veterinary Diet Urinary SO", "Bag 17.6lb", "Veterinary Diet", "Clinical Dog"),
            ("Veterinary Diet Gastrointestinal", "Bag 22lb", "Veterinary Diet", "Clinical Dog"),
            ("Kitten Dry", "Bag 7lb", "Lifestage", "Premium Cat"),
            ("Indoor Adult Cat", "Bag 15lb", "Lifestage", "Premium Cat"),
            ("Veterinary Diet Renal Support", "Bag 6.6lb", "Veterinary Diet", "Clinical Cat"),
            ("Size Health Nutrition Medium Adult", "Bag 30lb", "Size Health", "Premium Dog"),
            ("Aging 12+ Senior Cat", "Bag 6lb", "Lifestage", "Premium Cat"),
            ("Hydrolyzed Protein HP", "Bag 25.3lb", "Veterinary Diet", "Clinical Dog"),
        ]
    },
    "IAMS": {
        "gbu": "Petcare", "ec_group": "Pet Food", "technology": "Dry",
        "supply_tech": "Extrusion", "segment": "Dog Food",
        "business_segment": "Premium Mainstream", "market_segment": "Dog Dry Premium",
        "products": [
            ("ProActive Health Adult", "Bag 15lb", "Dry Dog Food", "Dog Nutrition"),
            ("ProActive Health Puppy", "Bag 15lb", "Dry Dog Food", "Dog Nutrition"),
            ("ProActive Health Senior", "Bag 15lb", "Dry Dog Food", "Dog Nutrition"),
            ("Healthy Adult Cat Chicken", "Bag 16lb", "Dry Cat Food", "Cat Nutrition"),
        ]
    },
    "Nutro": {
        "gbu": "Petcare", "ec_group": "Natural Pet Food", "technology": "Dry",
        "supply_tech": "Natural Extrusion", "segment": "Natural Pet",
        "business_segment": "Natural & Organic", "market_segment": "Natural Dog",
        "products": [
            ("Wholesome Essentials Adult Lamb", "Bag 30lb", "Natural Dog Food", "Natural Dog"),
            ("Ultra Adult Dry Dog", "Bag 15lb", "Natural Dog Food", "Natural Dog"),
            ("Max Adult Cat Chicken", "Bag 13lb", "Natural Cat Food", "Natural Cat"),
            ("Grain Free Adult Duck", "Bag 24lb", "Natural Dog Food", "Natural Dog"),
        ]
    },
    "M&M's": {
        "gbu": "Snacking", "ec_group": "Chocolate", "technology": "Panning",
        "supply_tech": "Sugar Panning", "segment": "Chocolate Confectionery",
        "business_segment": "Core Chocolate", "market_segment": "Chocolate Bitesize",
        "products": [
            ("Milk Chocolate", "Bag 10.7oz", "Chocolate Bags", "Bitesize Chocolate"),
            ("Peanut", "Bag 10.7oz", "Chocolate Bags", "Bitesize Chocolate"),
            ("Peanut Butter", "Bag 9.6oz", "Chocolate Bags", "Bitesize Chocolate"),
            ("Caramel", "Bag 9.05oz", "Chocolate Bags", "Bitesize Chocolate"),
            ("Crispy", "Bag 8oz", "Chocolate Bags", "Bitesize Chocolate"),
            ("Minis Mix Sharing", "Bag 10.1oz", "Chocolate Bags", "Bitesize Chocolate"),
            ("Fudge Brownie", "Bag 8oz", "Chocolate Bags", "Bitesize Chocolate"),
        ]
    },
    "Snickers": {
        "gbu": "Snacking", "ec_group": "Chocolate", "technology": "Enrobing",
        "supply_tech": "Caramel Nougat Line", "segment": "Chocolate Confectionery",
        "business_segment": "Core Chocolate", "market_segment": "Chocolate Bars",
        "products": [
            ("Original Bar", "Bar 1.86oz", "Chocolate Bars", "Countline"),
            ("King Size", "Bar 3.7oz", "Chocolate Bars", "Countline"),
            ("Almond Bar", "Bar 1.76oz", "Chocolate Bars", "Countline"),
            ("Ice Cream Bar", "Bar 2oz", "Ice Cream", "Frozen Snacks"),
            ("Fun Size 6pk", "Pack 6ct", "Chocolate Bags", "Bitesize Chocolate"),
            ("Creamy Peanut Butter", "Bar 1.8oz", "Chocolate Bars", "Countline"),
        ]
    },
    "Twix": {
        "gbu": "Snacking", "ec_group": "Chocolate", "technology": "Enrobing",
        "supply_tech": "Biscuit Caramel Line", "segment": "Chocolate Confectionery",
        "business_segment": "Core Chocolate", "market_segment": "Chocolate Bars",
        "products": [
            ("Original Caramel", "Bar 1.79oz", "Chocolate Bars", "Countline"),
            ("Peanut Butter", "Bar 1.68oz", "Chocolate Bars", "Countline"),
            ("Cookies & Creme", "Bar 1.36oz", "Chocolate Bars", "Countline"),
            ("Fun Size 12pk", "Pack 12ct", "Chocolate Bags", "Bitesize Chocolate"),
        ]
    },
    "Milky Way": {
        "gbu": "Snacking", "ec_group": "Chocolate", "technology": "Enrobing",
        "supply_tech": "Nougat Line", "segment": "Chocolate Confectionery",
        "business_segment": "Core Chocolate", "market_segment": "Chocolate Bars",
        "products": [
            ("Original Bar", "Bar 1.84oz", "Chocolate Bars", "Countline"),
            ("Midnight Dark", "Bar 1.76oz", "Chocolate Bars", "Countline"),
            ("Simply Caramel", "Bar 1.91oz", "Chocolate Bars", "Countline"),
        ]
    },
    "Dove": {
        "gbu": "Snacking", "ec_group": "Chocolate", "technology": "Moulding",
        "supply_tech": "Moulded Chocolate", "segment": "Premium Chocolate",
        "business_segment": "Premium Chocolate", "market_segment": "Chocolate Premium",
        "products": [
            ("Milk Chocolate Promises", "Bag 8.46oz", "Premium Bags", "Premium Bitesize"),
            ("Dark Chocolate Promises", "Bag 8.46oz", "Premium Bags", "Premium Bitesize"),
            ("Caramel Milk Chocolate", "Bag 7.61oz", "Premium Bags", "Premium Bitesize"),
            ("Milk Chocolate Bar", "Bar 3.3oz", "Premium Bars", "Premium Countline"),
        ]
    },
    "Skittles": {
        "gbu": "Snacking", "ec_group": "Sugar Confectionery", "technology": "Panning",
        "supply_tech": "Sugar Panning", "segment": "Sugar Confectionery",
        "business_segment": "Fruity Confections", "market_segment": "Fruity Candy",
        "products": [
            ("Original", "Bag 9oz", "Candy Bags", "Fruity Bitesize"),
            ("Wild Berry", "Bag 9oz", "Candy Bags", "Fruity Bitesize"),
            ("Tropical", "Bag 9oz", "Candy Bags", "Fruity Bitesize"),
            ("Sour", "Bag 7.2oz", "Candy Bags", "Fruity Bitesize"),
        ]
    },
    "Starburst": {
        "gbu": "Snacking", "ec_group": "Sugar Confectionery", "technology": "Cooking",
        "supply_tech": "Chewy Candy Line", "segment": "Sugar Confectionery",
        "business_segment": "Fruity Confections", "market_segment": "Chewy Candy",
        "products": [
            ("Original Fruit Chews", "Pack 2.07oz", "Candy Packs", "Chewy Candy"),
            ("FaveREDs", "Bag 8oz", "Candy Bags", "Chewy Candy"),
            ("Tropical", "Pack 2.07oz", "Candy Packs", "Chewy Candy"),
        ]
    },
    "Extra": {
        "gbu": "Snacking", "ec_group": "Gum", "technology": "Gum Base",
        "supply_tech": "Gum Extrusion", "segment": "Gum & Mints",
        "business_segment": "Gum", "market_segment": "Gum",
        "products": [
            ("Spearmint Sugar Free", "Pack 15ct", "Gum Packs", "Sugar Free Gum"),
            ("Polar Ice Sugar Free", "Pack 15ct", "Gum Packs", "Sugar Free Gum"),
            ("Winterfresh", "Pack 15ct", "Gum Packs", "Sugar Free Gum"),
            ("Sweet Watermelon", "Pack 15ct", "Gum Packs", "Sugar Free Gum"),
        ]
    },
    "Orbit": {
        "gbu": "Snacking", "ec_group": "Gum", "technology": "Gum Base",
        "supply_tech": "Gum Tableting", "segment": "Gum & Mints",
        "business_segment": "Gum", "market_segment": "Gum International",
        "products": [
            ("Peppermint", "Pack 14ct", "Gum Packs", "Sugar Free Gum"),
            ("Spearmint", "Pack 14ct", "Gum Packs", "Sugar Free Gum"),
            ("Bubblemint", "Pack 14ct", "Gum Packs", "Sugar Free Gum"),
        ]
    },
    "Uncle Ben's": {
        "gbu": "Food Nutrition & Multisales", "ec_group": "Rice", "technology": "Parboil",
        "supply_tech": "Parboiled Rice", "segment": "Ambient Food",
        "business_segment": "Rice & Grains", "market_segment": "Rice",
        "products": [
            ("Original Long Grain White", "Box 2lb", "Dry Rice", "White Rice"),
            ("Whole Grain Brown", "Box 2lb", "Dry Rice", "Brown Rice"),
            ("Basmati", "Box 2lb", "Dry Rice", "Specialty Rice"),
            ("Ready Rice Original", "Pouch 8.8oz", "Microwave Rice", "Convenience Rice"),
            ("Ready Rice Jasmine", "Pouch 8.8oz", "Microwave Rice", "Convenience Rice"),
            ("Ready Rice Spanish Style", "Pouch 8.8oz", "Microwave Rice", "Flavored Rice"),
        ]
    },
    "Dolmio": {
        "gbu": "Food Nutrition & Multisales", "ec_group": "Sauces", "technology": "Cooking",
        "supply_tech": "Sauce Processing", "segment": "Ambient Food",
        "business_segment": "Sauces & Meal Kits", "market_segment": "Pasta Sauce",
        "products": [
            ("Bolognese Original", "Jar 500g", "Pasta Sauces", "Bolognese"),
            ("Bolognese Extra Mushroom", "Jar 500g", "Pasta Sauces", "Bolognese"),
            ("Lasagne White Sauce", "Jar 470g", "Pasta Sauces", "White Sauce"),
            ("Stir In Sun Dried Tomato", "Pouch 150g", "Stir In Sauces", "Stir In"),
        ]
    },
    "Seeds of Change": {
        "gbu": "Food Nutrition & Multisales", "ec_group": "Organic", "technology": "Cooking",
        "supply_tech": "Organic Processing", "segment": "Organic Food",
        "business_segment": "Organic & Natural", "market_segment": "Organic Rice",
        "products": [
            ("Organic Quinoa & Brown Rice", "Pouch 8.5oz", "Organic Rice", "Organic Grains"),
            ("Organic Brown Basmati Rice", "Pouch 8.5oz", "Organic Rice", "Organic Grains"),
        ]
    },
    "Masterfoods": {
        "gbu": "Food Nutrition & Multisales", "ec_group": "Sauces", "technology": "Cooking",
        "supply_tech": "Sauce Processing", "segment": "Ambient Food",
        "business_segment": "Sauces & Meal Kits", "market_segment": "Table Sauces",
        "products": [
            ("BBQ Sauce", "Bottle 500ml", "Table Sauces", "BBQ"),
            ("Tomato Sauce", "Bottle 500ml", "Table Sauces", "Ketchup"),
            ("Mustard", "Bottle 250ml", "Table Sauces", "Mustard"),
        ]
    },
    "5 Gum": {
        "gbu": "Wrigley", "ec_group": "Gum", "technology": "Gum Base",
        "supply_tech": "Gum Extrusion", "segment": "Premium Gum",
        "business_segment": "Premium Gum", "market_segment": "Premium Gum",
        "products": [
            ("Peppermint Cobalt", "Pack 15ct", "Premium Gum Packs", "Premium Gum"),
            ("Spearmint Rain", "Pack 15ct", "Premium Gum Packs", "Premium Gum"),
            ("Wintermint Ascent", "Pack 15ct", "Premium Gum Packs", "Premium Gum"),
        ]
    },
    "Altoids": {
        "gbu": "Wrigley", "ec_group": "Mints", "technology": "Tableting",
        "supply_tech": "Mint Pressing", "segment": "Gum & Mints",
        "business_segment": "Mints", "market_segment": "Mints",
        "products": [
            ("Peppermint", "Tin 1.76oz", "Mint Tins", "Strong Mints"),
            ("Wintergreen", "Tin 1.76oz", "Mint Tins", "Strong Mints"),
            ("Cinnamon", "Tin 1.76oz", "Mint Tins", "Strong Mints"),
        ]
    },
    "Lifesavers": {
        "gbu": "Wrigley", "ec_group": "Sugar Confectionery", "technology": "Hard Candy",
        "supply_tech": "Hard Candy Line", "segment": "Sugar Confectionery",
        "business_segment": "Hard Candy", "market_segment": "Hard Candy",
        "products": [
            ("5 Flavors Hard Candy", "Bag 6.25oz", "Hard Candy Bags", "Ring Candy"),
            ("Wint-O-Green Mints", "Bag 6.25oz", "Mint Bags", "Mints"),
        ]
    },
}

# Build composite item rows (same logic as Databricks version)
composite_rows = []  # list of dicts for later reuse
brand_id_map = {}
brand_counter = 1000

for brand_name, brand_info in brand_products.items():
    brand_id = brand_counter
    brand_id_map[brand_name] = brand_id
    brand_counter += 10

    for idx, (prod_name, pack_format, prod_consol, prod_cat) in enumerate(brand_info["products"]):
        comp_id = f"CI_{gen_entity_id(brand_name + prod_name)}"
        composite_rows.append({
            "Composite_Item_ID": comp_id,
            "EC_Group": brand_info["ec_group"],
            "Technology": brand_info["technology"],
            "Supply_Tech": brand_info["supply_tech"],
            "Segment": brand_info["segment"],
            "Business_Segment": brand_info["business_segment"],
            "Market_Segment": brand_info["market_segment"],
            "Brand_ID": brand_id,
            "Brand": brand_name,
            "Consumer_Pack_Format": pack_format,
            "Product_Consolidation": prod_consol,
            "Product_Category": prod_cat,
        })

composite_db_rows = [(c["Composite_Item_ID"], c["EC_Group"], c["Technology"], c["Supply_Tech"],
                       c["Segment"], c["Business_Segment"], c["Market_Segment"], c["Brand_ID"],
                       c["Brand"], c["Consumer_Pack_Format"], c["Product_Consolidation"],
                       c["Product_Category"]) for c in composite_rows]

cur.executemany("INSERT INTO finiq_composite_item VALUES (?,?,?,?,?,?,?,?,?,?,?,?)", composite_db_rows)
table_counts["finiq_composite_item"] = len(composite_db_rows)
print(f"  Wrote finiq_composite_item: {len(composite_db_rows)} rows")

# ============================================================================
# TABLE 7: finiq_item (15 cols)
# ============================================================================
print("\nCreating TABLE 7: finiq_item ...")

cur.execute("""
CREATE TABLE finiq_item (
    Item_ID                                 TEXT    NOT NULL,
    EC_Group_ID                             INTEGER,
    EC_Group_Alias                          TEXT,
    Brand_Flag_ID                           INTEGER,
    Brand_Flag_Alias                        TEXT,
    Financial_Product_Segment_ID            INTEGER,
    Financial_Product_Segment_Alias         TEXT,
    Market_Segment_ID                       INTEGER,
    Market_Segment_Alias                    TEXT,
    Supply_Tech_ID                          INTEGER,
    Supply_Tech_Alias                       TEXT,
    Business_Segment_ID                     TEXT,
    Business_Segment_Alias                  TEXT,
    Product_Category_Consolidation_ID       TEXT,
    Product_Category_Consolidation_Alias    TEXT
)
""")

# Build segment/group ID maps from composite items
ec_group_ids = {}
brand_flag_ids = {}
fin_prod_seg_ids = {}
market_seg_ids = {}
supply_tech_ids = {}
bus_seg_ids = {}
prod_cat_ids = {}

for ci_row in composite_rows:
    if ci_row["EC_Group"] not in ec_group_ids:
        ec_group_ids[ci_row["EC_Group"]] = len(ec_group_ids) + 100
    if ci_row["Brand"] not in brand_flag_ids:
        brand_flag_ids[ci_row["Brand"]] = ci_row["Brand_ID"]
    if ci_row["Segment"] not in fin_prod_seg_ids:
        fin_prod_seg_ids[ci_row["Segment"]] = len(fin_prod_seg_ids) + 200
    if ci_row["Market_Segment"] not in market_seg_ids:
        market_seg_ids[ci_row["Market_Segment"]] = len(market_seg_ids) + 300
    if ci_row["Supply_Tech"] not in supply_tech_ids:
        supply_tech_ids[ci_row["Supply_Tech"]] = len(supply_tech_ids) + 400
    if ci_row["Business_Segment"] not in bus_seg_ids:
        bus_seg_ids[ci_row["Business_Segment"]] = f"BS{len(bus_seg_ids) + 1:03d}"
    if ci_row["Product_Category"] not in prod_cat_ids:
        prod_cat_ids[ci_row["Product_Category"]] = f"PC{len(prod_cat_ids) + 1:03d}"

item_rows = []
item_counter = 1
for ci_row in composite_rows:
    item_id = f"ITM{item_counter:06d}"
    item_rows.append((
        item_id,
        ec_group_ids[ci_row["EC_Group"]],
        ci_row["EC_Group"],
        brand_flag_ids[ci_row["Brand"]],
        ci_row["Brand"],
        fin_prod_seg_ids[ci_row["Segment"]],
        ci_row["Segment"],
        market_seg_ids[ci_row["Market_Segment"]],
        ci_row["Market_Segment"],
        supply_tech_ids[ci_row["Supply_Tech"]],
        ci_row["Supply_Tech"],
        bus_seg_ids[ci_row["Business_Segment"]],
        ci_row["Business_Segment"],
        prod_cat_ids[ci_row["Product_Category"]],
        ci_row["Product_Category"],
    ))
    item_counter += 1

cur.executemany("INSERT INTO finiq_item VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)", item_rows)
table_counts["finiq_item"] = len(item_rows)
print(f"  Wrote finiq_item: {len(item_rows)} rows")

# ============================================================================
# TABLE 8: finiq_item_composite_item (3 cols)
# ============================================================================
print("\nCreating TABLE 8: finiq_item_composite_item ...")

cur.execute("""
CREATE TABLE finiq_item_composite_item (
    Item_ID             TEXT    NOT NULL,
    Composite_Item_ID   TEXT    NOT NULL,
    IT_EC_Group_ID      INTEGER
)
""")

bridge_rows = []
for i, (item_row, ci_row) in enumerate(zip(item_rows, composite_rows)):
    bridge_rows.append((item_row[0], ci_row["Composite_Item_ID"], item_row[1]))

cur.executemany("INSERT INTO finiq_item_composite_item VALUES (?,?,?)", bridge_rows)
table_counts["finiq_item_composite_item"] = len(bridge_rows)
print(f"  Wrote finiq_item_composite_item: {len(bridge_rows)} rows")

# ============================================================================
# TABLE 9: finiq_customer (11 cols)
# ============================================================================
print("\nCreating TABLE 9: finiq_customer ...")

cur.execute("""
CREATE TABLE finiq_customer (
    Entity_Customer_ID  TEXT NOT NULL,
    Customer_ID         TEXT NOT NULL,
    Country             TEXT,
    Customer_Name       TEXT,
    SCM_ID              TEXT,
    Customer_Level_1    TEXT,
    Customer_Level_2    TEXT,
    Customer_Level_3    TEXT,
    Customer_Channel    TEXT,
    Customer_Format     TEXT,
    Customer_Subformat  TEXT
)
""")

customer_definitions = [
    ("US", "Walmart", "Mass Retail", "Hypermarket", "Mass", "Hypermarket", "Large Format"),
    ("US", "Target", "Mass Retail", "Discount Store", "Mass", "Discount", "Large Format"),
    ("US", "Kroger", "Grocery", "Supermarket Chain", "Grocery", "Supermarket", "Full Service"),
    ("US", "Costco", "Warehouse Club", "Club Store", "Club", "Warehouse", "Bulk"),
    ("US", "Sam's Club", "Warehouse Club", "Club Store", "Club", "Warehouse", "Bulk"),
    ("US", "Publix", "Grocery", "Regional Supermarket", "Grocery", "Supermarket", "Full Service"),
    ("US", "Albertsons", "Grocery", "Supermarket Chain", "Grocery", "Supermarket", "Full Service"),
    ("US", "Ahold Delhaize US", "Grocery", "Supermarket Chain", "Grocery", "Supermarket", "Full Service"),
    ("US", "HEB", "Grocery", "Regional Supermarket", "Grocery", "Supermarket", "Full Service"),
    ("US", "Dollar General", "Discount", "Dollar Store", "Value", "Dollar", "Small Format"),
    ("US", "Dollar Tree", "Discount", "Dollar Store", "Value", "Dollar", "Small Format"),
    ("US", "CVS", "Drug Store", "Pharmacy Chain", "Drug", "Pharmacy", "Convenience"),
    ("US", "Walgreens", "Drug Store", "Pharmacy Chain", "Drug", "Pharmacy", "Convenience"),
    ("US", "PetSmart", "Specialty Pet", "Pet Specialty", "Pet", "Pet Store", "Specialty"),
    ("US", "Petco", "Specialty Pet", "Pet Specialty", "Pet", "Pet Store", "Specialty"),
    ("US", "Chewy.com", "E-Commerce", "Online Pet", "Online", "E-Commerce", "Digital"),
    ("US", "Amazon US", "E-Commerce", "Marketplace", "Online", "E-Commerce", "Digital"),
    ("US", "Whole Foods", "Premium Grocery", "Natural & Organic", "Premium", "Natural", "Full Service"),
    ("US", "7-Eleven US", "Convenience", "C-Store Chain", "Convenience", "C-Store", "Small Format"),
    ("UK", "Tesco", "Grocery", "Supermarket Chain", "Grocery", "Supermarket", "Full Service"),
    ("UK", "Sainsbury's", "Grocery", "Supermarket Chain", "Grocery", "Supermarket", "Full Service"),
    ("UK", "ASDA", "Grocery", "Supermarket Chain", "Grocery", "Hypermarket", "Large Format"),
    ("UK", "Morrisons", "Grocery", "Supermarket Chain", "Grocery", "Supermarket", "Full Service"),
    ("UK", "Pets at Home", "Specialty Pet", "Pet Specialty", "Pet", "Pet Store", "Specialty"),
    ("UK", "Aldi UK", "Discount", "Hard Discount", "Value", "Discount", "Limited Assortment"),
    ("UK", "Lidl UK", "Discount", "Hard Discount", "Value", "Discount", "Limited Assortment"),
    ("DE", "REWE Group", "Grocery", "Supermarket Chain", "Grocery", "Supermarket", "Full Service"),
    ("DE", "Edeka", "Grocery", "Supermarket Chain", "Grocery", "Supermarket", "Full Service"),
    ("DE", "Aldi Germany", "Discount", "Hard Discount", "Value", "Discount", "Limited Assortment"),
    ("DE", "Lidl Germany", "Discount", "Hard Discount", "Value", "Discount", "Limited Assortment"),
    ("DE", "dm-drogerie markt", "Drug Store", "Drugstore", "Drug", "Drugstore", "Specialty"),
    ("FR", "Carrefour", "Grocery", "Hypermarket Chain", "Grocery", "Hypermarket", "Large Format"),
    ("FR", "Leclerc", "Grocery", "Hypermarket Chain", "Grocery", "Hypermarket", "Large Format"),
    ("FR", "Auchan", "Grocery", "Hypermarket Chain", "Grocery", "Hypermarket", "Large Format"),
    ("AU", "Woolworths AU", "Grocery", "Supermarket Chain", "Grocery", "Supermarket", "Full Service"),
    ("AU", "Coles", "Grocery", "Supermarket Chain", "Grocery", "Supermarket", "Full Service"),
    ("CN", "RT-Mart", "Grocery", "Hypermarket Chain", "Grocery", "Hypermarket", "Large Format"),
    ("CN", "Freshippo (Hema)", "E-Commerce", "New Retail", "Online", "New Retail", "Omnichannel"),
    ("CN", "JD.com", "E-Commerce", "Marketplace", "Online", "E-Commerce", "Digital"),
    ("JP", "AEON", "Grocery", "Supermarket Chain", "Grocery", "Supermarket", "Full Service"),
    ("JP", "Seven & I Holdings", "Convenience", "C-Store Chain", "Convenience", "C-Store", "Small Format"),
    ("BR", "Grupo Pao de Acucar", "Grocery", "Supermarket Chain", "Grocery", "Supermarket", "Full Service"),
    ("BR", "Carrefour Brazil", "Grocery", "Hypermarket Chain", "Grocery", "Hypermarket", "Large Format"),
    ("MX", "Walmex", "Mass Retail", "Hypermarket", "Mass", "Hypermarket", "Large Format"),
    ("MX", "OXXO", "Convenience", "C-Store Chain", "Convenience", "C-Store", "Small Format"),
    ("IN", "Reliance Retail", "Mass Retail", "Modern Trade", "Modern Trade", "Supermarket", "Full Service"),
    ("IN", "BigBasket", "E-Commerce", "Online Grocery", "Online", "E-Commerce", "Digital"),
    ("AE", "Carrefour UAE", "Grocery", "Hypermarket Chain", "Grocery", "Hypermarket", "Large Format"),
    ("SA", "Panda Retail", "Grocery", "Supermarket Chain", "Grocery", "Supermarket", "Full Service"),
    ("ZA", "Shoprite Holdings", "Grocery", "Supermarket Chain", "Grocery", "Supermarket", "Full Service"),
    ("ZA", "Pick n Pay", "Grocery", "Supermarket Chain", "Grocery", "Supermarket", "Full Service"),
    ("US", "McLane Company", "Wholesale", "Distributor", "Wholesale", "Distributor", "Wholesale"),
    ("US", "Core-Mark", "Wholesale", "Distributor", "Wholesale", "Distributor", "Wholesale"),
    ("UK", "Bestway Wholesale", "Wholesale", "Cash & Carry", "Wholesale", "Cash & Carry", "Wholesale"),
    ("DE", "METRO AG", "Wholesale", "Cash & Carry", "Wholesale", "Cash & Carry", "Wholesale"),
    ("FR", "Transgourmet", "Wholesale", "Distributor", "Wholesale", "Distributor", "Wholesale"),
]

customer_rows = []  # list of dicts for reuse
customer_db_rows = []
for idx, (country, name, lvl1, lvl2, lvl3, channel, fmt) in enumerate(customer_definitions):
    cust_id = f"CUST{idx + 1:04d}"
    entity_cust_id = f"EC_{country}_{cust_id}"
    scm_id = f"SCM{idx + 1:06d}"
    subformat = f"{fmt} - {channel}"

    customer_rows.append({
        "Entity_Customer_ID": entity_cust_id,
        "Customer_ID": cust_id,
        "Country": country,
        "Customer_Name": name,
        "SCM_ID": scm_id,
        "Customer_Level_1": lvl1,
        "Customer_Level_2": lvl2,
        "Customer_Level_3": lvl3,
        "Customer_Channel": channel,
        "Customer_Format": fmt,
        "Customer_Subformat": subformat,
    })

    customer_db_rows.append((
        entity_cust_id, cust_id, country, name, scm_id,
        lvl1, lvl2, lvl3, channel, fmt, subformat
    ))

cur.executemany("INSERT INTO finiq_customer VALUES (?,?,?,?,?,?,?,?,?,?,?)", customer_db_rows)
table_counts["finiq_customer"] = len(customer_db_rows)
print(f"  Wrote finiq_customer: {len(customer_db_rows)} rows")

# ============================================================================
# TABLE 10: finiq_customer_map (5 cols)
# ============================================================================
print("\nCreating TABLE 10: finiq_customer_map ...")

cur.execute("""
CREATE TABLE finiq_customer_map (
    Child_Entity_ID     TEXT NOT NULL,
    Child_Customer_ID   TEXT NOT NULL,
    Parent_Entity_ID    TEXT NOT NULL,
    Parent_Customer_ID  TEXT NOT NULL,
    Entity_Customer_ID  TEXT NOT NULL
)
""")

cust_map_db_rows = []
for c_row in customer_rows:
    parent_ent_id = mars_id
    for e_row in entity_rows:
        if c_row["Country"] in e_row[3] and e_row[4] >= 4:  # Child_Entity, Entity_Level
            parent_ent_id = e_row[2]  # Child_Entity_ID
            break

    cust_map_db_rows.append((
        parent_ent_id,
        c_row["Customer_ID"],
        mars_id,
        "CUST_ALL",
        c_row["Entity_Customer_ID"],
    ))

cur.executemany("INSERT INTO finiq_customer_map VALUES (?,?,?,?,?)", cust_map_db_rows)
table_counts["finiq_customer_map"] = len(cust_map_db_rows)
print(f"  Wrote finiq_customer_map: {len(cust_map_db_rows)} rows")

# ============================================================================
# TABLE 11: finiq_economic_cell (3 cols)
# ============================================================================
print("\nCreating TABLE 11: finiq_economic_cell ...")

cur.execute("""
CREATE TABLE finiq_economic_cell (
    Economic_Cell_ID  INTEGER NOT NULL,
    Economic_Cell     TEXT    NOT NULL,
    Archetype         TEXT    NOT NULL
)
""")

ec_data = [
    (1,  "Gross Revenue",         "Revenue"),
    (2,  "Trade Spend",           "Revenue Deduction"),
    (3,  "Net Revenue",           "Revenue"),
    (4,  "Raw Materials",         "Variable Cost"),
    (5,  "Packaging",             "Variable Cost"),
    (6,  "Manufacturing Labor",   "Variable Cost"),
    (7,  "Manufacturing Overhead","Fixed Cost"),
    (8,  "Distribution",          "Variable Cost"),
    (9,  "Advertising",           "Fixed Cost"),
    (10, "Consumer Promotions",   "Fixed Cost"),
    (11, "R&D",                   "Fixed Cost"),
    (12, "Selling",               "Fixed Cost"),
    (13, "General Admin",         "Fixed Cost"),
    (14, "Depreciation",          "Non-Cash"),
    (15, "Capital Expenditure",   "Investment"),
    (16, "Working Capital",       "Balance Sheet"),
    (17, "Inventory",             "Balance Sheet"),
    (18, "Accounts Receivable",   "Balance Sheet"),
    (19, "Accounts Payable",      "Balance Sheet"),
    (20, "Other Cash Items",      "Non-Cash"),
]

cur.executemany("INSERT INTO finiq_economic_cell VALUES (?,?,?)", ec_data)
table_counts["finiq_economic_cell"] = len(ec_data)
print(f"  Wrote finiq_economic_cell: {len(ec_data)} rows")

# ============================================================================
# FACT TABLE COMMON SETUP
# ============================================================================
print("\nPreparing fact table generation ...")

random.seed(SEED)

# Collect dimension keys for fact generation
all_entity_ids = [e[2] for e in entity_rows if e[4] == 5]  # sub-units only (Child_Entity_ID where Entity_Level==5)
all_account_ids = [a[0] for a in accounts_data]
account_sign_map = {a[0]: a[4] for a in accounts_data}
account_name_map = {a[0]: a[1] for a in accounts_data}
account_parent_map = {a[0]: a[2] for a in accounts_data}
account_parent_name_map = {a[0]: a[3] for a in accounts_data}
account_stmt_map = {a[0]: a[5] for a in accounts_data}

# Entity lookup
entity_id_to_name = {e[2]: e[3] for e in entity_rows}  # Child_Entity_ID -> Child_Entity
entity_id_to_parent = {e[2]: e[1] for e in entity_rows}  # -> Parent_Entity
entity_id_to_level = {e[2]: e[4] for e in entity_rows}  # -> Entity_Level

# Date lookup
date_id_map = {d[0]: d for d in date_rows}  # Date_ID -> (Date_ID, Year, Period, Quarter)

# Composite item subset for fact tables (pick 20 representative products)
representative_composites = composite_rows[:20]
composite_id_list = [c["Composite_Item_ID"] for c in representative_composites]
composite_info_map = {c["Composite_Item_ID"]: c for c in representative_composites}

# Customer subset (pick 15 representative customers)
representative_customers = customer_rows[:15]
customer_id_list = [c["Entity_Customer_ID"] for c in representative_customers]
customer_info_map = {c["Entity_Customer_ID"]: c for c in representative_customers}

# Economic cell subset
ec_id_list = [e[0] for e in ec_data[:10]]

print(f"  Sub-unit entities: {len(all_entity_ids)}")
print(f"  Account codes: {len(all_account_ids)}")
print(f"  Composite items for facts: {len(composite_id_list)}")
print(f"  Customers for facts: {len(customer_id_list)}")

# ============================================================================
# TABLE 12: finiq_financial (39 cols) — denormalized wide fact table
# ============================================================================
print("\nCreating TABLE 12: finiq_financial ...")

cur.execute("""
CREATE TABLE finiq_financial (
    Date_ID             INTEGER NOT NULL,
    Year                INTEGER NOT NULL,
    Period              TEXT    NOT NULL,
    Quarter             TEXT    NOT NULL,
    Parent_Entity       TEXT,
    Entity              TEXT,
    Entity_Level        INTEGER,
    Parent_Account      TEXT,
    Account_KPI         TEXT,
    Statement           TEXT,
    EC_Group            TEXT,
    Brand               TEXT,
    Segment             TEXT,
    Market_Segment      TEXT,
    Technology          TEXT,
    Supply_Tech         TEXT,
    Product_Consolidation TEXT,
    Product_Category    TEXT,
    Business_Segment    TEXT,
    Pack_Format         TEXT,
    Economic_Cell       TEXT,
    Archetype           TEXT,
    Customer_ID         TEXT,
    Country             TEXT,
    Customer_Name       TEXT,
    SCM_ID              TEXT,
    Customer_Level_1    TEXT,
    Customer_Level_2    TEXT,
    Customer_Level_3    TEXT,
    Customer_Channel    TEXT,
    Customer_Format     TEXT,
    Customer_Subformat  TEXT,
    Currency            TEXT,
    Sign_Conversion     INTEGER,
    Entity_ID           TEXT,
    Account_ID          TEXT,
    Brand_ID            INTEGER,
    USD_Value           REAL,
    Local_Value         REAL
)
""")

# Use a subset of entities: all GBU-level + some sub-units
financial_entities = [(e[2], e[3], e[4], e[1]) for e in entity_rows if e[4] in (1, 2, 3)]
sub_units = [(e[2], e[3], e[4], e[1]) for e in entity_rows if e[4] == 5][:10]
financial_entities.extend(sub_units)

default_composite = composite_rows[0]
default_customer = customer_rows[0]

financial_db_rows = []
for ent_id, ent_name, ent_level, parent_name in financial_entities:
    currency = get_currency(ent_name)
    fx = fx_rates.get(currency, 1.0)

    for date_row in date_rows:
        date_id, year, period, quarter = date_row

        for acct_id, acct_name, parent_ids, parent_names, sign, stmts in accounts_data:
            usd_val = generate_base_revenue(ent_id, date_id, acct_id)
            level_scale = {1: 50.0, 2: 15.0, 3: 5.0, 4: 2.0, 5: 1.0}
            usd_val *= level_scale.get(ent_level, 1.0)
            local_val = round(usd_val / fx, 2) if fx != 1.0 else usd_val

            financial_db_rows.append((
                date_id, year, period, quarter,
                parent_name, ent_name, ent_level,
                json.dumps(parent_names),  # array -> JSON
                acct_name,
                json.dumps(stmts),         # array -> JSON
                default_composite["EC_Group"],
                default_composite["Brand"],
                default_composite["Segment"],
                default_composite["Market_Segment"],
                default_composite["Technology"],
                default_composite["Supply_Tech"],
                default_composite["Product_Consolidation"],
                default_composite["Product_Category"],
                default_composite["Business_Segment"],
                default_composite["Consumer_Pack_Format"],
                ec_data[0][1],  # Economic_Cell
                ec_data[0][2],  # Archetype
                default_customer["Customer_ID"],
                default_customer["Country"],
                default_customer["Customer_Name"],
                default_customer["SCM_ID"],
                default_customer["Customer_Level_1"],
                default_customer["Customer_Level_2"],
                default_customer["Customer_Level_3"],
                default_customer["Customer_Channel"],
                default_customer["Customer_Format"],
                default_customer["Customer_Subformat"],
                currency, sign, ent_id, acct_id,
                default_composite["Brand_ID"],
                float(usd_val), float(local_val),
            ))

cur.executemany(
    "INSERT INTO finiq_financial VALUES (" + ",".join(["?"] * 39) + ")",
    financial_db_rows
)
table_counts["finiq_financial"] = len(financial_db_rows)
print(f"  Wrote finiq_financial: {len(financial_db_rows)} rows")

conn.commit()

# ============================================================================
# TABLE 13: finiq_financial_base (7 cols)
# ============================================================================
print("\nCreating TABLE 13: finiq_financial_base ...")

cur.execute("""
CREATE TABLE finiq_financial_base (
    Date_ID             INTEGER NOT NULL,
    Entity_ID           TEXT    NOT NULL,
    Account_ID          TEXT    NOT NULL,
    Composite_Item_ID   TEXT,
    Economic_Cell_ID    INTEGER,
    Entity_Customer_ID  TEXT,
    USD_Value           REAL
)
""")

base_db_rows = []
for entity_id in all_entity_ids[:20]:
    for date_row in date_rows:
        for acct_id in all_account_ids[:15]:
            for ci_id in composite_id_list[:5]:
                ec_id = random.choice(ec_id_list)
                ec_cust_id = random.choice(customer_id_list)
                usd_val = generate_base_revenue(entity_id, date_row[0], acct_id)

                base_db_rows.append((
                    date_row[0], entity_id, acct_id, ci_id,
                    ec_id, ec_cust_id, float(usd_val),
                ))

cur.executemany("INSERT INTO finiq_financial_base VALUES (?,?,?,?,?,?,?)", base_db_rows)
table_counts["finiq_financial_base"] = len(base_db_rows)
print(f"  Wrote finiq_financial_base: {len(base_db_rows)} rows")

conn.commit()

# ============================================================================
# TABLE 14: finiq_financial_cons (9 cols) — USED BY VIEWS
# ============================================================================
print("\nCreating TABLE 14: finiq_financial_cons ...")

cur.execute("""
CREATE TABLE finiq_financial_cons (
    Date_ID             INTEGER NOT NULL,
    Entity_ID           TEXT    NOT NULL,
    Account_ID          TEXT    NOT NULL,
    Composite_Item_ID   TEXT,
    Economic_Cell_ID    INTEGER,
    Entity_Customer_ID  TEXT,
    Currency_ID         TEXT,
    USD_Value           REAL,
    Local_Value         REAL
)
""")

cons_db_rows = []
for entity_id in all_entity_ids[:20]:
    ent_name = entity_id_to_name.get(entity_id, "Unknown")
    currency = get_currency(ent_name)
    fx = fx_rates.get(currency, 1.0)

    for date_row in date_rows:
        for acct_id in all_account_ids[:15]:
            for ci_id in composite_id_list[:5]:
                ec_id = random.choice(ec_id_list)
                ec_cust_id = random.choice(customer_id_list)
                usd_val = generate_base_revenue(entity_id, date_row[0], acct_id)
                local_val = round(usd_val / fx, 2) if fx != 1.0 else usd_val

                cons_db_rows.append((
                    date_row[0], entity_id, acct_id, ci_id,
                    ec_id, ec_cust_id, currency,
                    float(usd_val), float(local_val),
                ))

cur.executemany("INSERT INTO finiq_financial_cons VALUES (?,?,?,?,?,?,?,?,?)", cons_db_rows)
table_counts["finiq_financial_cons"] = len(cons_db_rows)
print(f"  Wrote finiq_financial_cons: {len(cons_db_rows)} rows")

conn.commit()

# ============================================================================
# TABLE 15: finiq_financial_replan (18 cols)
# ============================================================================
print("\nCreating TABLE 15: finiq_financial_replan ...")

cur.execute("""
CREATE TABLE finiq_financial_replan (
    Submission_Type_ID  INTEGER NOT NULL,
    Date_ID             INTEGER NOT NULL,
    Year                INTEGER NOT NULL,
    Quarter             TEXT    NOT NULL,
    Parent_Entity       TEXT,
    Entity              TEXT,
    Entity_Level        INTEGER,
    Parent_Account      TEXT,
    Account_KPI         TEXT,
    Statement           TEXT,
    Currency            TEXT,
    Sign_Conversion     INTEGER,
    Entity_ID           TEXT,
    Account_ID          TEXT,
    Actual_USD_Value    REAL,
    Actual_Local_Value  REAL,
    Replan_USD_Value    REAL,
    Replan_Local_Value  REAL
)
""")

replan_entities = [(e[2], e[3], e[4], e[1]) for e in entity_rows if e[4] in (1, 2, 3)]
replan_entities.extend(sub_units[:5])

submission_types = [1, 2]

replan_db_rows = []
for sub_type in submission_types:
    for ent_id, ent_name, ent_level, parent_name in replan_entities:
        currency = get_currency(ent_name)
        fx = fx_rates.get(currency, 1.0)

        for date_row in date_rows:
            date_id, year_val, period_val, quarter = date_row

            for acct_id, acct_name, parent_ids, parent_names, sign, stmts in accounts_data:
                actual_usd = generate_base_revenue(ent_id, date_id, acct_id)
                level_scale = {1: 50.0, 2: 15.0, 3: 5.0, 4: 2.0, 5: 1.0}
                actual_usd *= level_scale.get(ent_level, 1.0)
                actual_local = round(actual_usd / fx, 2) if fx != 1.0 else actual_usd

                rng = random.Random(hash((ent_id, date_id, acct_id, sub_type)) % 2**31)
                variance_factor = rng.uniform(0.90, 1.10)
                replan_usd = round(actual_usd * variance_factor, 2)
                replan_local = round(replan_usd / fx, 2) if fx != 1.0 else replan_usd

                replan_db_rows.append((
                    sub_type, date_id, year_val, quarter,
                    parent_name, ent_name, ent_level,
                    json.dumps(parent_names),
                    acct_name,
                    json.dumps(stmts),
                    currency, sign, ent_id, acct_id,
                    float(actual_usd), float(actual_local),
                    float(replan_usd), float(replan_local),
                ))

cur.executemany(
    "INSERT INTO finiq_financial_replan VALUES (" + ",".join(["?"] * 18) + ")",
    replan_db_rows
)
table_counts["finiq_financial_replan"] = len(replan_db_rows)
print(f"  Wrote finiq_financial_replan: {len(replan_db_rows)} rows")

conn.commit()

# ============================================================================
# TABLE 16: finiq_financial_replan_cons (6 cols)
# ============================================================================
print("\nCreating TABLE 16: finiq_financial_replan_cons ...")

cur.execute("""
CREATE TABLE finiq_financial_replan_cons (
    Date_ID      INTEGER NOT NULL,
    Entity_ID    TEXT    NOT NULL,
    Account_ID   TEXT    NOT NULL,
    Currency_ID  TEXT,
    USD_Value    REAL,
    Local_Value  REAL
)
""")

replan_cons_db_rows = []
for entity_id in all_entity_ids[:10]:
    ent_name = entity_id_to_name.get(entity_id, "Unknown")
    currency = get_currency(ent_name)
    fx = fx_rates.get(currency, 1.0)

    for date_row in date_rows:
        for acct_id in all_account_ids[:10]:
            usd_val = generate_base_revenue(entity_id, date_row[0], acct_id)
            rng_r = random.Random(hash((entity_id, date_row[0], acct_id, "replan_cons")) % 2**31)
            usd_val *= rng_r.uniform(0.92, 1.08)
            local_val = round(usd_val / fx, 2) if fx != 1.0 else usd_val

            replan_cons_db_rows.append((
                date_row[0], entity_id, acct_id, currency,
                float(round(usd_val, 2)), float(local_val),
            ))

cur.executemany("INSERT INTO finiq_financial_replan_cons VALUES (?,?,?,?,?,?)", replan_cons_db_rows)
table_counts["finiq_financial_replan_cons"] = len(replan_cons_db_rows)
print(f"  Wrote finiq_financial_replan_cons: {len(replan_cons_db_rows)} rows")

conn.commit()

# ============================================================================
# TABLE 17: finiq_rls_last_change (2 cols)
# ============================================================================
print("\nCreating TABLE 17: finiq_rls_last_change ...")

cur.execute("""
CREATE TABLE finiq_rls_last_change (
    Last_Change  TEXT    NOT NULL,
    Version      INTEGER NOT NULL
)
""")

cur.execute("INSERT INTO finiq_rls_last_change VALUES (?,?)",
            ("2026-03-26T10:30:00", 1))
table_counts["finiq_rls_last_change"] = 1
print(f"  Wrote finiq_rls_last_change: 1 rows")

conn.commit()

# ============================================================================
# VIEW 18: finiq_vw_ncfo_entity (7 output cols)
# ============================================================================
print("\nCreating VIEW 18: finiq_vw_ncfo_entity ...")

cur.execute("""
CREATE VIEW finiq_vw_ncfo_entity AS
WITH ncfo_accounts AS (
    SELECT Child_Account_ID AS Account_ID, Child_Account AS Account_Name
    FROM finiq_dim_account
    WHERE Statement LIKE '%NCFO%'
),
periodic_cy AS (
    SELECT
        f.Entity,
        f.Entity_ID,
        f.Account_KPI,
        f.Account_ID,
        f.Year,
        f.Period,
        f.USD_Value AS Periodic_CY
    FROM finiq_financial f
    WHERE f.Year = 2025
      AND f.Entity_Level <= 3
      AND EXISTS (SELECT 1 FROM ncfo_accounts na WHERE na.Account_ID = f.Account_ID)
),
periodic_ly AS (
    SELECT
        f.Entity,
        f.Entity_ID,
        f.Account_KPI,
        f.Account_ID,
        f.Year,
        f.Period,
        f.USD_Value AS Periodic_LY
    FROM finiq_financial f
    WHERE f.Year = 2024
      AND f.Entity_Level <= 3
      AND EXISTS (SELECT 1 FROM ncfo_accounts na WHERE na.Account_ID = f.Account_ID)
),
ytd_cy AS (
    SELECT
        Entity, Entity_ID, Account_KPI, Account_ID, Period,
        SUM(USD_Value) OVER (PARTITION BY Entity_ID, Account_ID ORDER BY Period) AS YTD_CY
    FROM finiq_financial
    WHERE Year = 2025
      AND Entity_Level <= 3
      AND Account_ID IN (SELECT Account_ID FROM ncfo_accounts)
),
ytd_ly AS (
    SELECT
        Entity, Entity_ID, Account_KPI, Account_ID, Period,
        SUM(USD_Value) OVER (PARTITION BY Entity_ID, Account_ID ORDER BY Period) AS YTD_LY
    FROM finiq_financial
    WHERE Year = 2024
      AND Entity_Level <= 3
      AND Account_ID IN (SELECT Account_ID FROM ncfo_accounts)
)
SELECT
    cy.Entity,
    cy.Account_KPI,
    cy.Period,
    COALESCE(ytd_ly.YTD_LY, 0) AS YTD_LY,
    COALESCE(ytd_cy.YTD_CY, 0) AS YTD_CY,
    COALESCE(ly.Periodic_LY, 0) AS Periodic_LY,
    cy.Periodic_CY
FROM periodic_cy cy
LEFT JOIN periodic_ly ly
    ON cy.Entity_ID = ly.Entity_ID
    AND cy.Account_ID = ly.Account_ID
    AND cy.Period = ly.Period
LEFT JOIN ytd_cy
    ON cy.Entity_ID = ytd_cy.Entity_ID
    AND cy.Account_ID = ytd_cy.Account_ID
    AND cy.Period = ytd_cy.Period
LEFT JOIN ytd_ly
    ON cy.Entity_ID = ytd_ly.Entity_ID
    AND cy.Account_ID = ytd_ly.Account_ID
    AND cy.Period = ytd_ly.Period
""")
print(f"  Created view: finiq_vw_ncfo_entity")

# ============================================================================
# VIEW 19: finiq_vw_pl_entity (7 output cols)
# ============================================================================
print("\nCreating VIEW 19: finiq_vw_pl_entity ...")

cur.execute("""
CREATE VIEW finiq_vw_pl_entity AS
WITH pl_accounts AS (
    SELECT Child_Account_ID AS Account_ID, Child_Account AS Account_Name
    FROM finiq_dim_account
    WHERE Statement LIKE '%P&L%'
),
periodic_cy AS (
    SELECT f.Entity, f.Entity_ID, f.Account_KPI, f.Account_ID, f.Year, f.Period,
           f.USD_Value AS Periodic_CY
    FROM finiq_financial f
    WHERE f.Year = 2025 AND f.Entity_Level <= 3
      AND EXISTS (SELECT 1 FROM pl_accounts pa WHERE pa.Account_ID = f.Account_ID)
),
periodic_ly AS (
    SELECT f.Entity, f.Entity_ID, f.Account_KPI, f.Account_ID, f.Year, f.Period,
           f.USD_Value AS Periodic_LY
    FROM finiq_financial f
    WHERE f.Year = 2024 AND f.Entity_Level <= 3
      AND EXISTS (SELECT 1 FROM pl_accounts pa WHERE pa.Account_ID = f.Account_ID)
),
ytd_cy AS (
    SELECT Entity, Entity_ID, Account_KPI, Account_ID, Period,
           SUM(USD_Value) OVER (PARTITION BY Entity_ID, Account_ID ORDER BY Period) AS YTD_CY
    FROM finiq_financial
    WHERE Year = 2025 AND Entity_Level <= 3
      AND Account_ID IN (SELECT Account_ID FROM pl_accounts)
),
ytd_ly AS (
    SELECT Entity, Entity_ID, Account_KPI, Account_ID, Period,
           SUM(USD_Value) OVER (PARTITION BY Entity_ID, Account_ID ORDER BY Period) AS YTD_LY
    FROM finiq_financial
    WHERE Year = 2024 AND Entity_Level <= 3
      AND Account_ID IN (SELECT Account_ID FROM pl_accounts)
)
SELECT
    cy.Entity,
    cy.Account_KPI,
    cy.Period,
    COALESCE(ytd_ly.YTD_LY, 0) AS YTD_LY,
    COALESCE(ytd_cy.YTD_CY, 0) AS YTD_CY,
    COALESCE(ly.Periodic_LY, 0) AS Periodic_LY,
    cy.Periodic_CY
FROM periodic_cy cy
LEFT JOIN periodic_ly ly
    ON cy.Entity_ID = ly.Entity_ID AND cy.Account_ID = ly.Account_ID AND cy.Period = ly.Period
LEFT JOIN ytd_cy
    ON cy.Entity_ID = ytd_cy.Entity_ID AND cy.Account_ID = ytd_cy.Account_ID AND cy.Period = ytd_cy.Period
LEFT JOIN ytd_ly
    ON cy.Entity_ID = ytd_ly.Entity_ID AND cy.Account_ID = ytd_ly.Account_ID AND cy.Period = ytd_ly.Period
""")
print(f"  Created view: finiq_vw_pl_entity")

# ============================================================================
# VIEW 20: finiq_vw_pl_brand_product (8 output cols)
# ============================================================================
print("\nCreating VIEW 20: finiq_vw_pl_brand_product ...")

cur.execute("""
CREATE VIEW finiq_vw_pl_brand_product AS
WITH pl_accounts AS (
    SELECT Child_Account_ID AS Account_ID
    FROM finiq_dim_account
    WHERE Statement LIKE '%P&L%'
),
brand_cy AS (
    SELECT Entity, Brand, Account_KPI, Account_ID, Period,
           SUM(USD_Value) AS Periodic_CY
    FROM finiq_financial
    WHERE Year = 2025 AND Entity_Level <= 3
      AND Account_ID IN (SELECT Account_ID FROM pl_accounts)
    GROUP BY Entity, Brand, Account_KPI, Account_ID, Period
),
brand_ly AS (
    SELECT Entity, Brand, Account_KPI, Account_ID, Period,
           SUM(USD_Value) AS Periodic_LY
    FROM finiq_financial
    WHERE Year = 2024 AND Entity_Level <= 3
      AND Account_ID IN (SELECT Account_ID FROM pl_accounts)
    GROUP BY Entity, Brand, Account_KPI, Account_ID, Period
),
ytd_brand_cy AS (
    SELECT Entity, Brand, Account_KPI, Account_ID, Period,
           SUM(SUM(USD_Value)) OVER (
               PARTITION BY Entity, Brand, Account_ID ORDER BY Period
           ) AS YTD_CY
    FROM finiq_financial
    WHERE Year = 2025 AND Entity_Level <= 3
      AND Account_ID IN (SELECT Account_ID FROM pl_accounts)
    GROUP BY Entity, Brand, Account_KPI, Account_ID, Period
),
ytd_brand_ly AS (
    SELECT Entity, Brand, Account_KPI, Account_ID, Period,
           SUM(SUM(USD_Value)) OVER (
               PARTITION BY Entity, Brand, Account_ID ORDER BY Period
           ) AS YTD_LY
    FROM finiq_financial
    WHERE Year = 2024 AND Entity_Level <= 3
      AND Account_ID IN (SELECT Account_ID FROM pl_accounts)
    GROUP BY Entity, Brand, Account_KPI, Account_ID, Period
)
SELECT
    cy.Entity,
    cy.Brand,
    cy.Account_KPI,
    cy.Period,
    COALESCE(ytd_ly.YTD_LY, 0) AS YTD_LY,
    COALESCE(ytd_cy.YTD_CY, 0) AS YTD_CY,
    COALESCE(ly.Periodic_LY, 0) AS Periodic_LY,
    cy.Periodic_CY
FROM brand_cy cy
LEFT JOIN brand_ly ly
    ON cy.Entity = ly.Entity AND cy.Brand = ly.Brand
    AND cy.Account_ID = ly.Account_ID AND cy.Period = ly.Period
LEFT JOIN ytd_brand_cy ytd_cy
    ON cy.Entity = ytd_cy.Entity AND cy.Brand = ytd_cy.Brand
    AND cy.Account_ID = ytd_cy.Account_ID AND cy.Period = ytd_cy.Period
LEFT JOIN ytd_brand_ly ytd_ly
    ON cy.Entity = ytd_ly.Entity AND cy.Brand = ytd_ly.Brand
    AND cy.Account_ID = ytd_ly.Account_ID AND cy.Period = ytd_ly.Period
""")
print(f"  Created view: finiq_vw_pl_brand_product")

conn.commit()

# ============================================================================
# VALIDATION & SUMMARY
# ============================================================================

print("\n" + "=" * 70)
print("FINIQ SYNTHETIC DATA GENERATION -- VALIDATION REPORT")
print("=" * 70)
print(f"Database:     {DB_PATH}")
print(f"Seed:         {SEED}")
print(f"Fiscal Years: {FISCAL_YEARS}")
print("=" * 70)

all_tables = [
    "finiq_date",
    "finiq_dim_entity",
    "finiq_dim_account",
    "finiq_account_formula",
    "finiq_account_input",
    "finiq_composite_item",
    "finiq_item",
    "finiq_item_composite_item",
    "finiq_customer",
    "finiq_customer_map",
    "finiq_economic_cell",
    "finiq_financial",
    "finiq_financial_base",
    "finiq_financial_cons",
    "finiq_financial_replan",
    "finiq_financial_replan_cons",
    "finiq_rls_last_change",
]

all_views = [
    "finiq_vw_ncfo_entity",
    "finiq_vw_pl_entity",
    "finiq_vw_pl_brand_product",
]

total_rows = 0
print(f"\n{'Object':<40} {'Type':<8} {'Rows':>15}")
print("-" * 65)

for tbl in all_tables:
    cur.execute(f"SELECT COUNT(*) FROM {tbl}")
    count = cur.fetchone()[0]
    total_rows += count
    print(f"{tbl:<40} {'TABLE':<8} {count:>15,}")

for view in all_views:
    try:
        cur.execute(f"SELECT COUNT(*) FROM {view}")
        count = cur.fetchone()[0]
        total_rows += count
        print(f"{view:<40} {'VIEW':<8} {count:>15,}")
    except Exception as e:
        print(f"{view:<40} {'VIEW':<8} {'ERROR':>15} -- {str(e)[:40]}")

print("-" * 65)
print(f"{'TOTAL':<40} {'':8} {total_rows:>15,}")

# Database file size
db_size_mb = os.path.getsize(DB_PATH) / (1024 * 1024)
print(f"\nDatabase file size: {db_size_mb:.1f} MB")
print(f"\nSynthetic data generation complete.")
print(f"All 17 tables + 3 views created in {DB_PATH}")

conn.close()
